import 'package:starflow/features/discovery/domain/douban_models.dart';
import 'package:starflow/features/library/domain/media_models.dart';
import 'package:starflow/features/settings/domain/app_settings.dart';
import 'package:starflow/features/search/domain/search_models.dart';

class SeedData {
  static final AppSettings defaultSettings = AppSettings(
    mediaSources: const [
      MediaSourceConfig(
        id: 'emby-main',
        name: '家里 Emby',
        kind: MediaSourceKind.emby,
        endpoint: 'https://emby.example.com',
        enabled: true,
        username: 'starflow',
        accessToken: '',
      ),
      MediaSourceConfig(
        id: 'nas-living-room',
        name: '客厅 NAS 网关',
        kind: MediaSourceKind.nas,
        endpoint: 'https://nas.example.com/media',
        enabled: true,
      ),
    ],
    searchProviders: const [
      SearchProviderConfig(
        id: 'jackett-main',
        name: 'Jackett 聚合',
        kind: SearchProviderKind.indexer,
        endpoint: 'https://jackett.example.com/api',
        enabled: true,
        parserHint: 'torznab',
      ),
      SearchProviderConfig(
        id: 'mikan-anime',
        name: 'Mikan 动漫',
        kind: SearchProviderKind.torrent,
        endpoint: 'https://mikan.example.com/search',
        enabled: true,
      ),
    ],
    doubanAccount: const DoubanAccountConfig(
      enabled: true,
      userId: 'demo-user',
      sessionCookie: '',
    ),
    homeModules: const [
      HomeModuleConfig(
        id: 'module-douban-recommendations',
        type: HomeModuleType.doubanRecommendations,
        title: '豆瓣推荐',
        enabled: true,
      ),
      HomeModuleConfig(
        id: 'module-douban-wish',
        type: HomeModuleType.doubanWishList,
        title: '豆瓣想看',
        enabled: true,
      ),
      HomeModuleConfig(
        id: 'module-recently-added',
        type: HomeModuleType.recentlyAdded,
        title: '最近新增',
        enabled: true,
      ),
      HomeModuleConfig(
        id: 'module-emby-library',
        type: HomeModuleType.embyLibrary,
        title: 'Emby 片库',
        enabled: true,
      ),
      HomeModuleConfig(
        id: 'module-nas-library',
        type: HomeModuleType.nasLibrary,
        title: 'NAS 片库',
        enabled: true,
      ),
    ],
  );

  static final List<MediaItem> seedLibrary = [
    MediaItem(
      id: 'media-dune',
      title: '沙丘',
      overview: '保罗踏入厄拉科斯的命运之旅，适合作为科幻大屏体验片。',
      posterUrl: 'https://picsum.photos/seed/dune1/400/600',
      year: 2021,
      durationLabel: '2h 35m',
      genres: const ['科幻', '冒险'],
      sourceId: 'emby-main',
      sourceName: '家里 Emby',
      sourceKind: MediaSourceKind.emby,
      streamUrl: 'https://emby.example.com/Videos/dune/master.m3u8',
      addedAt: DateTime(2026, 3, 28),
      lastWatchedAt: DateTime(2026, 4, 1),
    ),
    MediaItem(
      id: 'media-dune2',
      title: '沙丘2',
      overview: '延续厄拉科斯战争史诗，适合作为首页主推内容。',
      posterUrl: 'https://picsum.photos/seed/dune2/400/600',
      year: 2024,
      durationLabel: '2h 46m',
      genres: const ['科幻', '史诗'],
      sourceId: 'emby-main',
      sourceName: '家里 Emby',
      sourceKind: MediaSourceKind.emby,
      streamUrl: 'https://emby.example.com/Videos/dune2/master.m3u8',
      addedAt: DateTime(2026, 4, 2),
    ),
    MediaItem(
      id: 'media-oppenheimer',
      title: '奥本海默',
      overview: '人物传记与核时代焦虑交织，适合作为剧情片展示。',
      posterUrl: 'https://picsum.photos/seed/oppenheimer/400/600',
      year: 2023,
      durationLabel: '3h 0m',
      genres: const ['剧情', '历史'],
      sourceId: 'emby-main',
      sourceName: '家里 Emby',
      sourceKind: MediaSourceKind.emby,
      streamUrl: 'https://emby.example.com/Videos/oppenheimer/master.m3u8',
      addedAt: DateTime(2026, 3, 16),
    ),
    MediaItem(
      id: 'media-wandering-earth-2',
      title: '流浪地球2',
      overview: '中国科幻工业大片，适合和豆瓣推荐联动。',
      posterUrl: 'https://picsum.photos/seed/wanderingearth2/400/600',
      year: 2023,
      durationLabel: '2h 53m',
      genres: const ['科幻', '灾难'],
      sourceId: 'nas-living-room',
      sourceName: '客厅 NAS 网关',
      sourceKind: MediaSourceKind.nas,
      streamUrl: 'https://nas.example.com/media/stream/wandering-earth-2.m3u8',
      addedAt: DateTime(2026, 4, 3),
    ),
    MediaItem(
      id: 'media-blade-runner-2049',
      title: '银翼杀手2049',
      overview: '氛围感极强的赛博朋克影像，适合大屏播放。',
      posterUrl: 'https://picsum.photos/seed/bladerunner/400/600',
      year: 2017,
      durationLabel: '2h 44m',
      genres: const ['科幻', '悬疑'],
      sourceId: 'nas-living-room',
      sourceName: '客厅 NAS 网关',
      sourceKind: MediaSourceKind.nas,
      streamUrl: 'https://nas.example.com/media/stream/blade-runner-2049.m3u8',
      addedAt: DateTime(2026, 3, 10),
      lastWatchedAt: DateTime(2026, 3, 15),
    ),
    MediaItem(
      id: 'media-flourish',
      title: '繁花',
      overview: '都市群像与时代质感兼具，适合作为剧集展示样例。',
      posterUrl: 'https://picsum.photos/seed/flourish/400/600',
      year: 2023,
      durationLabel: '30 集',
      genres: const ['剧情', '剧集'],
      sourceId: 'emby-main',
      sourceName: '家里 Emby',
      sourceKind: MediaSourceKind.emby,
      streamUrl: 'https://emby.example.com/Videos/flourish/master.m3u8',
      addedAt: DateTime(2026, 3, 30),
    ),
    MediaItem(
      id: 'media-the-batman',
      title: '新蝙蝠侠',
      overview: '黑色侦探气质浓厚，适合作为暗调风格展示。',
      posterUrl: 'https://picsum.photos/seed/thebatman/400/600',
      year: 2022,
      durationLabel: '2h 56m',
      genres: const ['动作', '犯罪'],
      sourceId: 'nas-living-room',
      sourceName: '客厅 NAS 网关',
      sourceKind: MediaSourceKind.nas,
      streamUrl: 'https://nas.example.com/media/stream/the-batman.m3u8',
      addedAt: DateTime(2026, 3, 24),
    ),
    MediaItem(
      id: 'media-spiderverse',
      title: '蜘蛛侠：纵横宇宙',
      overview: '高色彩密度动画，适合作为演示素材。',
      posterUrl: 'https://picsum.photos/seed/spiderverse/400/600',
      year: 2023,
      durationLabel: '2h 20m',
      genres: const ['动画', '冒险'],
      sourceId: 'emby-main',
      sourceName: '家里 Emby',
      sourceKind: MediaSourceKind.emby,
      streamUrl: 'https://emby.example.com/Videos/spiderverse/master.m3u8',
      addedAt: DateTime(2026, 4, 1),
    ),
  ];

  static final List<DoubanEntry> seedDoubanRecommendations = const [
    DoubanEntry(
      id: 'db-rec-1',
      title: '沙丘2',
      year: 2024,
      posterUrl: 'https://picsum.photos/seed/douban-dune2/400/600',
      note: '朋友口碑很高，适合 IMAX 观感。',
    ),
    DoubanEntry(
      id: 'db-rec-2',
      title: '奥本海默',
      year: 2023,
      posterUrl: 'https://picsum.photos/seed/douban-oppenheimer/400/600',
      note: '最近讨论度很高，剧情张力强。',
    ),
    DoubanEntry(
      id: 'db-rec-3',
      title: '银翼杀手2049',
      year: 2017,
      posterUrl: 'https://picsum.photos/seed/douban-br2049/400/600',
      note: '氛围感电影，很适合夜晚慢慢看。',
    ),
  ];

  static final List<DoubanEntry> seedDoubanWishList = const [
    DoubanEntry(
      id: 'db-wish-1',
      title: '流浪地球2',
      year: 2023,
      posterUrl: 'https://picsum.photos/seed/douban-we2/400/600',
      note: '一直想补的国产科幻大作。',
    ),
    DoubanEntry(
      id: 'db-wish-2',
      title: '新蝙蝠侠',
      year: 2022,
      posterUrl: 'https://picsum.photos/seed/douban-batman/400/600',
      note: '想找一个周末晚上完整看掉。',
    ),
    DoubanEntry(
      id: 'db-wish-3',
      title: '花束般的恋爱',
      year: 2021,
      posterUrl: 'https://picsum.photos/seed/douban-love/400/600',
      note: '本地还没有资源，后面可以去搜索补片。',
    ),
  ];
}
