// Generated by tool/generate_playback_policy.dart. Do not edit.
enum PlaybackPolicyValues {
  static let version = 3
  static let memoryRecentLimit = 20
  static let memoryResumeMinimumMs = 5000
  static let memoryResumeRemainingMs = 12000
  static let memoryCompletedRemainingMs = 8000
  static let memoryCompletedPermille = 985
  static let memoryUnknownCompletedPermille = 995
  static let maxPlayerAttempts = 3
  static let maxRuntimeRecoveries = 2
  static let startupHardLimitMs = 120000
  static let exoStartupHardLimitMs = 60000
  static let exoStartupNoProgressTimeoutMs = 30000
  static let bufferAdvanceMs = 1000
  static let bufferAdvancePercent = 1
  static let positionAdvanceMs = 250
  static let backwardSeekMs = 1000
  static let remoteErrorConfirmationMs = 15000
  static let localErrorConfirmationMs = 3000
  static let recoveryCooldownMs = 10000
  static let transientHttpStatuses: Set<Int> = [408, 425, 429]
  static let permanentHttpStatuses: Set<Int> = [400, 401, 403, 404, 405, 410, 416]
  static let refreshableHttpStatuses: Set<Int> = [401, 403, 404, 410]
}
