import 'dart:convert';
import 'dart:io';

// Run from the repository root. --check is used by contract tests/CI.
void main(List<String> args) {
  final values =
      jsonDecode(File('config/playback_policy.json').readAsStringSync())
          as Map<String, dynamic>;
  final dart = StringBuffer(
    '// Generated by tool/generate_playback_policy.dart. Do not edit.\n'
    'abstract final class PlaybackPolicyValues {\n',
  );
  final kotlin = StringBuffer(
    '// Generated by tool/generate_playback_policy.dart. Do not edit.\n'
    'package com.example.starflow\n\n'
    'internal object PlaybackPolicyValues {\n',
  );
  for (final entry in values.entries) {
    final value = entry.value;
    if (value is int) {
      dart.writeln('  static const int ${entry.key} = $value;');
      kotlin.writeln('    const val ${entry.key} = $value');
    } else if (value is List && value.every((v) => v is int)) {
      dart.writeln(
          '  static const Set<int> ${entry.key} = {${value.join(', ')}};');
      kotlin.writeln('    val ${entry.key} = setOf(${value.join(', ')})');
    } else {
      throw FormatException('Unsupported policy value: ${entry.key}');
    }
  }
  dart.writeln('}');
  kotlin.writeln('}');
  final outputs = {
    'lib/features/playback/application/playback_policy_values.dart': '$dart',
    'android/app/src/main/kotlin/com/example/starflow/PlaybackPolicyValues.kt':
        '$kotlin',
  };
  for (final entry in outputs.entries) {
    final file = File(entry.key);
    if (args.contains('--check')) {
      if (!file.existsSync() || file.readAsStringSync() != entry.value) {
        stderr.writeln('Playback policy is out of date: ${entry.key}');
        exitCode = 1;
      }
    } else {
      file.writeAsStringSync(entry.value);
    }
  }
}
