// Generated by tool/generate_playback_policy.dart. Do not edit.
package com.example.starflow

internal object PlaybackPolicyValues {
    const val version = 3
    const val memoryRecentLimit = 20
    const val memoryResumeMinimumMs = 5000
    const val memoryResumeRemainingMs = 12000
    const val memoryCompletedRemainingMs = 8000
    const val memoryCompletedPermille = 985
    const val memoryUnknownCompletedPermille = 995
    const val maxPlayerAttempts = 3
    const val maxRuntimeRecoveries = 2
    const val startupHardLimitMs = 120000
    const val exoStartupHardLimitMs = 60000
    const val exoStartupNoProgressTimeoutMs = 30000
    const val bufferAdvanceMs = 1000
    const val bufferAdvancePercent = 1
    const val positionAdvanceMs = 250
    const val backwardSeekMs = 1000
    const val remoteErrorConfirmationMs = 15000
    const val localErrorConfirmationMs = 3000
    const val recoveryCooldownMs = 10000
    val transientHttpStatuses = setOf(408, 425, 429)
    val permanentHttpStatuses = setOf(400, 401, 403, 404, 405, 410, 416)
    val refreshableHttpStatuses = setOf(401, 403, 404, 410)
}
