// Generated by tool/generate_playback_policy.dart. Do not edit.
abstract final class PlaybackPolicyValues {
  static const int version = 1;
  static const int maxPlayerAttempts = 3;
  static const int maxRuntimeRecoveries = 2;
  static const int startupHardLimitMs = 120000;
  static const int bufferAdvanceMs = 1000;
  static const int bufferAdvancePercent = 1;
  static const int positionAdvanceMs = 250;
  static const int backwardSeekMs = 1000;
  static const int remoteErrorConfirmationMs = 15000;
  static const int localErrorConfirmationMs = 3000;
  static const int recoveryCooldownMs = 10000;
  static const Set<int> transientHttpStatuses = {408, 425, 429};
  static const Set<int> permanentHttpStatuses = {400, 401, 403, 404, 405, 410, 416};
  static const Set<int> refreshableHttpStatuses = {401, 403, 404, 410};
}
